---
title: "Face Presence Analysis"
author: "Jeffrey Girard"
date: "2026-06-12"
format: 
  html:
    embed-resources: true
    page-layout: full
---

## Setup

```{r setup}
#| message: false

library(tidyverse)
library(rstan)
library(brms)
library(easystats)
library(ggeffects)
library(gt)
```

```{r data}
info <- read_rds("/mnt/datasets/SEEDLingS/2_PROCESSED/session_info.rds")
part <- read_rds("/mnt/datasets/SEEDLingS/2_PROCESSED/partface_coding.rds") |> 
  left_join(info, by = join_by(subject, wave, month))
full <- read_rds("/mnt/datasets/SEEDLingS/2_PROCESSED/fullface_coding.rds") |> 
  left_join(info, by = join_by(subject, wave, month))
```

## Partial Face Analyses

### Partial Face Summary

```{r df_part}
df_part <- 
  part |> 
  filter(part_duration > 0) |> 
  summarize(
    .by = c(subject, wave, month),
    sum_part = sum(part_duration),
    pct_part = sum_part / first(session_duration)
  ) |> 
  arrange(subject, wave) |> 
  mutate(
    .by = subject,
    window = row_number() - 1
  ) |> 
  complete(subject, window)
```

```{r describe_part}
describe_distribution(df_part, select = "pct_part") |> print_md()
ggplot(df_part, aes(x = pct_part)) +
  geom_histogram(na.rm = TRUE, color = "white", breaks = seq(0, 1, 0.025)) +
  scale_x_continuous(breaks = seq(0, 1, 0.2), labels = scales::percent) +
  labs(x = "Percent of Video with a Partial Face", y = "Video Count")
```

### Partial Face Null Model

```{r part_null}
part_null <- brm(
  formula = pct_part | mi() ~ 1 + (1 | subject),
  family = Beta(link = "logit", link_phi = "log"),
  data = df_part,
  iter = 10000,
  warmup = 9000,
  chains = 3,
  cores = 3,
  refresh = 0,
  init = 0,
  file = "part_null",
  control = list(adapt_delta = 0.99, max_treedepth = 12),
  backend = "cmdstanr",
  threads = threading(3)
)
variance_decomposition(part_null)
```

### Partial Face Linear Time Model

```{r part_linear}
#| warning: false

part_linear <- brm(
  formula = pct_part | mi() ~ 1 + window + (1 + window | subject),
  family = Beta(link = "logit", link_phi = "log"),
  data = df_part,
  prior = set_prior("normal(0, 0.5)", class = "b"),
  iter = 10000,
  warmup = 9000,
  chains = 3,
  cores = 3,
  refresh = 0,
  init = 0,
  file = "part_linear",
  control = list(adapt_delta = 0.99, max_treedepth = 12),
  backend = "cmdstanr",
  threads = threading(3)
)
```

```{r part_ppc}
#| warning: false

pp_check(part_linear, ndraws = 50)
```

```{r part_mpt}
model_parameters(part_linear, effects = "all") |> print_md()
```

```{r part_cep}
plot(
  conditional_effects(
    part_linear, 
    effects = "window", 
    int_conditions = list(window = 0:3)
  ), 
  plot = FALSE
)[[1]] +
  geom_point() +
  scale_y_continuous(
    labels = scales::percent,
    limits = c(0, 0.5)
  ) +
  scale_x_continuous(
    breaks = 0:3,
    labels = c("6-8 months", "9-11 months", "12-14 months", "15-17 months")
  ) +
  labs(x = "Age Window", y = "Percent of Video Frames with a Partial Face") +
  theme_bw(base_size = 10) +
  theme(plot.margin = margin(10, 10, 10, 10))
ggsave("ppl_window.png", width = 6.5, height = 4.0, units = "in", dpi = 300)
```

### Partial Face Monotonic Time Model

```{r part_monotonic}
#| warning: false

part_monotonic <- brm(
  formula = pct_part | mi() ~ 1 + mo(window) + (1 + mo(window) | subject),
  family = Beta(link = "logit", link_phi = "log"),
  data = df_part,
  prior = set_prior("normal(0, 0.5)", class = "b"),
  iter = 10000,
  warmup = 9000,
  chains = 3,
  cores = 3,
  refresh = 0,
  init = 0,
  file = "part_monotonic",
  control = list(adapt_delta = 0.99, max_treedepth = 12),
  backend = "cmdstanr",
  threads = threading(3)
)
```

```{r part_ppc2}
#| warning: false

pp_check(part_monotonic, ndraws = 50)
```

```{r part_mpt2}
model_parameters(part_monotonic, effects = "all") |> print_md()
```

```{r part_cep2}
plot(
  conditional_effects(
    part_monotonic, 
    effects = "window", 
    int_conditions = list(window = 0:3)
  ), 
  plot = FALSE
)[[1]] +
  geom_point() +
  scale_y_continuous(
    labels = scales::percent,
    limits = c(0.25, 0.40)
  ) +
  scale_x_continuous(
    breaks = 0:3,
    labels = c("6-8 months", "9-11 months", "12-14 months", "15-17 months")
  ) +
  labs(x = "Age Window", y = "Percent of Video Frames with a Partial Face") +
  theme_bw(base_size = 9)
ggsave("ppm_window.png", width = 6.5, height = 4.0, units = "in", dpi = 300)
```

## Full Face Analyses

### Full Face Summaries

```{r df_full}
df_full <- 
  full |> 
  filter(full_duration > 0) |> 
  summarize(
    .by = c(subject, wave, month),
    sum_full = sum(full_duration),
    pct_full = sum_full / first(session_duration)
  ) |> 
  arrange(subject, wave) |> 
  mutate(
    .by = subject,
    window = row_number()
  ) |> 
  complete(subject, window)
```

```{r describe_full}
describe_distribution(df_full, select = "pct_full") |> print_md()
ggplot(df_full, aes(x = pct_full)) +
  geom_histogram(na.rm = TRUE, color = "white", breaks = seq(0, 1, 0.025)) +
  scale_x_continuous(breaks = seq(0, 1, 0.2), labels = scales::percent) +
  labs(x = "Percent of Video Frames with a Full Face", y = "Video Count")
```

### Full Face Null Model

```{r full_null}
full_null <- brm(
  formula = pct_full | mi() ~ 1 + (1 | subject),
  family = Beta(link = "logit", link_phi = "log"),
  data = df_full,
  iter = 10000,
  warmup = 9000,
  chains = 3,
  cores = 3,
  refresh = 0,
  file = "full_null",
  control = list(adapt_delta = 0.99, max_treedepth = 12),
  backend = "cmdstanr",
  threads = threading(3)
)
variance_decomposition(full_null)
```

### Full Face Linear Time Model

```{r full_linear}
#| warning: false

full_linear <- brm(
  formula = pct_full | mi() ~ 1 + window + (1 + window | subject),
  family = Beta(link = "logit", link_phi = "log"),
  data = df_full,
  prior = set_prior("normal(0, 0.5)", class = "b"),
  iter = 10000,
  warmup = 9000,
  chains = 3,
  cores = 3,
  refresh = 0,
  init = 0,
  file = "full_linear",
  control = list(adapt_delta = 0.99, max_treedepth = 12),
  backend = "cmdstanr",
  threads = threading(3)
)
```

```{r full_ppc}
#| warning: false

pp_check(full_linear, ndraws = 50)
```

```{r full_mpt}
model_parameters(full_linear, effects = "all") |> print_md()
```

```{r full_cep}
plot(
  conditional_effects(
    full_linear, 
    effects = "window", 
    int_conditions = list(window = 0:3)
  ), 
  plot = FALSE
)[[1]] +
  geom_point() +
  scale_y_continuous(
    labels = scales::percent,
    limits = c(0, 0.06)
  ) +
  scale_x_continuous(
    breaks = 0:3,
    labels = c("6-8 months", "9-11 months", "12-14 months", "15-17 months")
  ) +
  labs(x = "Age Window", y = "Percent of Video Frames with a Full Face") +
  theme_bw(base_size = 10) +
  theme(plot.margin = margin(10, 10, 10, 10))
ggsave("fig2.png", width = 6.5, height = 4.0, units = "in", dpi = 300)
```

### Full Face Monotonic Time Model

```{r full_monotonic}
#| warning: false

full_monotonic <- brm(
  formula = pct_full | mi() ~ 1 + mo(window) + (1 + mo(window) | subject),
  family = Beta(link = "logit", link_phi = "log"),
  data = df_full,
  prior = set_prior("normal(0, 0.5)", class = "b"),
  iter = 10000,
  warmup = 9000,
  chains = 3,
  cores = 3,
  refresh = 0,
  init = 0,
  file = "full_monotonic",
  control = list(adapt_delta = 0.99, max_treedepth = 12),
  backend = "cmdstanr",
  threads = threading(3)
)
```

```{r full_ppc2}
#| warning: false

pp_check(full_monotonic, ndraws = 50)
```

```{r full_mpt2}
model_parameters(full_monotonic, effects = "all") |> print_md()
```

```{r full_cep2}
plot(conditional_effects(full_monotonic, effects = "window"), plot = FALSE)[[1]] +
  geom_point() +
  scale_y_continuous(
    labels = scales::percent,
    limits = c(0.025, 0.060)
  ) +
  scale_x_continuous(
    breaks = 0:3,
    labels = c("6-8 months", "9-11 months", "12-14 months", "15-17 months")
  ) +
  labs(x = "Age Window", y = "Percent of Video Frames with a Full Face") +
  theme_bw(base_size = 9)
ggsave("pfm_window.png", width = 6.5, height = 4.0, units = "in", dpi = 300)
```

## Descriptive Tables

```{r}
df_part |>
  drop_na() |>
  summarize(
      .by = wave,
      n = n(),
      Mean = mean(pct_part, na.rm = TRUE),
      SD = sd(pct_part, na.rm = TRUE),
      Median = median(pct_part, na.rm = TRUE),
      MAD = mad(pct_part, na.rm = TRUE)
  ) |>
  rename(Wave = wave) |>
  gt() |>
  tab_header(title = "Partial Faces") |>
  fmt_percent(columns = c("Mean", "SD", "Median", "MAD"))
```


```{r}
df_full |>
  drop_na() |>
  summarize(
      .by = wave,
      n = n(),
      Mean = mean(pct_full, na.rm = TRUE),
      SD = sd(pct_full, na.rm = TRUE),
      Median = median(pct_full, na.rm = TRUE),
      MAD = mad(pct_full, na.rm = TRUE)
  ) |>
  rename(Wave = wave) |>
  gt() |>
  tab_header(title = "Full Faces") |>
  fmt_percent(columns = c("Mean", "SD", "Median", "MAD"))
```

## Results Table

```{r}
models <- list(
  "Partial" = part_linear,
  "Full" = full_linear
)

res <- 
  map(
    models,
    \(x) { 
      describe_posterior(x, parameters = "window") |> 
      as_tibble() |> 
      transmute(
        Est. = Median,
        CL = CI_low,
        CU = CI_high,
        OR = exp(Est.),
        OR_CL = exp(CL),
        OR_CU = exp(CU),
        pval = 2 * (1 - pd)
      )
    }
  ) |> 
  list_rbind(names_to = "Outcome")

gt_table <- 
  gt(res) |> 
  fmt_number(
    columns = Est.:OR_CU, 
    decimals = 2
  ) |> 
  fmt(
    columns = pval,
    fns = \(x) {
      char_x <- sprintf("%.3f", x)
      char_x <- sub("^0\\.", ".", char_x)
      ifelse(x < 0.001, "<.001", char_x)
    }
  ) |> 
  cols_merge(
    columns = c(Est., CL, CU),
    pattern = "{1} ({2}, {3})"
  ) |> 
  cols_merge(
    columns = c(OR, OR_CL, OR_CU),
    pattern = "{1} ({2}, {3})"
  ) |> 
  cols_label(
    Est. = "Logit Scale",
    OR = "Odds Ratio",
    pval = "p-value"
  ) |> 
  cols_align(
    align = "center",
    columns = c(Est., OR)
  )

gt_table
```

