---
title: "Hypothesized Prototypes"
author: "Jeffrey Girard"
date: "2026-06-24"
format: 
  html:
    page-layout: full
embed-resources: true
---

## Setup

```{r setup}
#| message: false

library(tidyverse)
library(furrr)
library(gt)
library(facs) # remotes::install_github("jmgirard/facs")
library(ordbetareg)
library(easystats)
library(patchwork)

info <- 
  left_join(
    read_rds("/mnt/datasets/SEEDLingS/2_PROCESSED/session_info.rds"), 
    read_rds("facs_times.rds"), 
    by = c("subject", "wave")
  ) |> 
  filter(!(subject == 18 & wave == 6)) |> 
  mutate(
    valid_session = session_duration - vis - hat,
    valid_fullface = ffa - vis - hat,
    phase = if_else(wave %in% c(6, 9), "I", "II")
  )

valid_session_i <- info |> filter(phase == "I") |> pull(valid_session) |> sum()
valid_session_ii <- info |> filter(phase == "II") |> pull(valid_session) |> sum()
valid_fullface_i <- info |> filter(phase == "I") |> pull(valid_fullface) |> sum()
valid_fullface_ii <- info |> filter(phase == "II") |> pull(valid_fullface) |> sum()

facs <- 
  read_rds("/mnt/datasets/SEEDLingS/2_PROCESSED/facs_coding.rds") |> 
  left_join(info) |> 
  mutate(event_id = str_c(subject, wave, facs_id, sep = "_"))

project_scheme <- scheme(
  list(
    occurrence = c(1:2, 4:39),
    intensity = c(1:2, 4:39),
    asymmetry = c(1:2, 4:39)
  )
)

protos <- 
  prototypes |> 
  filter(is.na(emotion_type) | emotion_type != "compound") |> 
  mutate(
    emotion = if_else(emotion %in% c("anger", "angry"), "anger", emotion),
    emotion = if_else(emotion %in% c("confused", "confusion"), "confusion", emotion),
    emotion = if_else(emotion %in% c("desire", "desire food", "desire sex"), "desire", emotion),
    emotion = if_else(emotion %in% c("disgust", "disgusted"), "disgust", emotion),
    emotion = if_else(emotion %in% c("fear", "fearful"), "fear", emotion),
    emotion = if_else(emotion %in% c("happy", "happiness", "joy"), "happiness", emotion),
    emotion = if_else(emotion %in% c("sad", "sadness"), "sadness", emotion),
    emotion = if_else(emotion %in% c("surprise", "surprised"), "surprise", emotion)
  )
```

```{r}
find_missing_aus <- function(proto, scheme, stringify = TRUE) {
  proto_codes <- pull_numcodes(proto)
  scheme_codes <- scheme$occurrence
  missing_aus <- setdiff(proto_codes, scheme_codes)
  if (stringify) {
    paste(missing_aus, collapse = ", ")
  } else {
    missing_aus
  }
}

find_remaining_aus <- function(proto_code, missing_aus) {
  proto_aus <- tidy(proto_code)[[1]]$occurrence
  missing_aus <- str_split(missing_aus, ", ")[[1]]
  remaining_aus <- setdiff(proto_aus, missing_aus)
  if (length(remaining_aus) > 0) {
    coding(paste(remaining_aus, collapse = "+"))
  } else {
    NA_character_
  }
}

protos2 <-
  protos |> 
  arrange(emotion, source, config_num) |> 
  mutate(
    missing_aus = map_chr(code, \(x) find_missing_aus(x, project_scheme)),
    remaining_aus = map2_chr(code, missing_aus, \(x, y) find_remaining_aus(x, y))
  ) |> 
  filter(!is.na(remaining_aus))

write_csv(protos2, "proto_summary.csv", na = "")
```

## Find Duplicated Prototypes

```{r}
protos2 |> 
  summarize(
    .by = remaining_aus,
    n_emotions = n_distinct(emotion),
    emotions = str_c(unique(emotion), collapse = ", ")
  ) |> 
  arrange(desc(n_emotions), remaining_aus) |> 
  filter(n_emotions > 1) |> 
  gt()
```

## Count Prototypes

```{r}
plan("multisession", workers = 9)
occ_counts <- 
  facs |> 
  select(-month) |> 
  mutate(
    occ = future_map_chr(facs_code, function(x) {
      codes <- tidy(coding(x))[[1]]$occurrence
      paste(codes[codes %in% project_scheme$occurrence], collapse = "+")
    }),
    occ = na_if(occ, ""),
    occ = na_if(occ, "NA"),
    occ = coding(occ)
  )
occ_counts_nested <- 
  occ_counts |> 
  nest(
    .by = c(occ, wave), 
    events = c(subject, event_id, facs_duration, session_duration)
  )
```

```{r}
merged <-
  crossing(
    occ = coding(sort(unique(c(occ_counts_nested$occ, protos2$code)))), 
    wave = c(6, 9, 12, 15)
  ) |> 
  left_join(
    y = occ_counts_nested,
    by = join_by(occ, wave)
  ) |> 
  left_join(
    y = protos2 |> mutate(remaining_aus = coding(remaining_aus)),
    by = join_by(occ == remaining_aus),
    relationship = "many-to-many"
  )
```

```{r}
wave_totals <- 
  info |> 
  summarize(
    .by = wave,
    wave_session_total = sum(valid_session, na.rm = TRUE),
    wave_fullface_total = sum(valid_fullface, na.rm = TRUE)
  )

proto_waves <- 
  merged |> 
  drop_na(emotion) |> 
  summarize(
    .by = c(emotion, wave),
    all_events = list(bind_rows(events)),
    n_protos_total = n(),
    n_protos_occur = sum(map_lgl(events, \(x) !is.null(x))),
    n_subjects = map_int(
      all_events, 
      \(x) ifelse(nrow(x) > 0, length(unique(x$subject)), 0)
    ),
    n_events = map_int(
      all_events,
      \(x) ifelse(nrow(x) > 0, length(unique(x$event_id)), 0)
    ),
    total_sec = map_dbl(
      all_events,
      \(x) ifelse(nrow(x) > 0, sum(distinct(x)$facs_duration), 0)
    )
  ) |> 
  left_join(wave_totals, by = "wave") |> 
  mutate(phase = ifelse(wave %in% c(6, 9), "I", "II"), .before = wave) |> 
  mutate(
    session_pct = total_sec / wave_session_total,
    fullface_pct = total_sec / wave_fullface_total
  ) |> 
  arrange(emotion, wave)

proto_waves |> 
  select(-c(all_events, wave_session_total, wave_fullface_total)) |> 
  mutate(emotion = str_to_title(emotion)) |> 
  gt() |> 
  fmt_percent(columns = c(session_pct, fullface_pct), decimals = 2)
```

```{r}
#| fig-height: 4.0
#| fig-width: 6.5
proto_waves |> 
  mutate(
    Window = factor(
      wave, 
      levels = c(6, 9, 12, 15), 
      labels = c("6-8 months", "9-11 months", "12-14 months", "15-17 months")
    ),
    Phase = factor(phase, labels = c("Phase I (6–11 months)", "Phase II (12–17 months)")),
    Emotion = str_to_title(emotion)
  ) |> 
  ggplot(aes(x = Window, y = fullface_pct, color = Emotion, shape = Emotion, group = Emotion)) +
  facet_wrap(~Phase, scales = "free") +
  geom_line() + 
  geom_point(size = 2.5) +
  scale_x_discrete() +
  scale_y_continuous(labels = scales::percent) +
  scale_color_manual(values = scales::hue_pal()(21)) +
  scale_shape_manual(values = rep(c(21, 22, 24), length.out = 21)) +
  guides(color = guide_legend(ncol = 2), shape = guide_legend(ncol = 2)) +
  labs(x = "Age Window", y = "Percentage of Valid Full Face Video Frames", 
       color = "Emotion Category", shape = "Emotion Category") +
  theme_bw(base_size = 9)
ggsave("pct_window_emotion.png", width = 6.5, height = 4.0, units = "in", dpi = 300)
```

```{r}
#| fig-height: 7.0
#| fig-width: 6.5
phase_totals <- 
  info |> 
  summarize(
    .by = phase,
    phase_session_total = sum(valid_session, na.rm = TRUE),
    phase_fullface_total = sum(valid_fullface, na.rm = TRUE)
  ) |> 
  mutate(phase_ratio = phase_fullface_total / phase_session_total)

pwdat <- 
  proto_waves |> 
  mutate(
    Phase = factor(
      phase, 
      labels = c(
        "Phase I (6–11 months, includes primary caregiver)", 
        "Phase II (12–17 months, excludes primary caregiver)"
      )
    )
  ) |> 
  summarize(
    .by = c(phase, Phase, emotion), 
    total_sec = sum(total_sec)
  ) |> 
  left_join(phase_totals, by = "phase") |> 
  mutate(
    session_pct = total_sec / phase_session_total,
    fullface_pct = total_sec / phase_fullface_total,
    Emotion = fct_reorder(factor(str_to_title(emotion)), .x = fullface_pct)
  )

create_phase_plot <- function(phase_num) {
  
  pct_ratio <- phase_totals |> filter(phase == phase_num) |> pull(phase_ratio)
  data_subset <- filter(pwdat, phase == phase_num)
  phase_color <- if_else(phase_num == "I", "#66c2a5", "#fc8d62")
  
  ggplot(data_subset, aes(x = fullface_pct, y = Emotion)) +
    facet_wrap(~Phase) +
    geom_segment(
      color = phase_color, 
      aes(xend = 0, yend = Emotion), 
      linewidth = 3/4
    ) +
    geom_point(
      color = phase_color, 
      size = 2
    ) +
    scale_y_discrete(drop = FALSE) +
    scale_x_continuous(
      labels = scales::percent,
      sec.axis = sec_axis(
        transform = ~ . * pct_ratio,
        name = "Percentage of Valid Session Frames",
        labels = scales::percent,
        breaks = \(x) scales::breaks_extended()(x / pct_ratio) * pct_ratio
      )
    ) +
    labs(
      x = "Percentage of Valid Full Face Frames", 
      y = "Emotion Category"
    ) +
    theme_bw(base_size = 10) +
    theme(
      panel.grid.major.y = element_blank(),
      plot.margin = margin(10, 10, 10, 10)
    )
}

create_phase_plot("I") / create_phase_plot("II")
ggsave("fig3.png", width = 6.5, height = 7.0, units = "in", dpi = 300)
```


```{r}
proto_waves |> 
  summarize(
    .by = c(phase, emotion), 
    total_sec = sum(total_sec)
  ) |>
  left_join(phase_totals, by = "phase") |> 
  mutate(
    session_pct = total_sec / phase_session_total,
    fullface_pct = total_sec / phase_fullface_total
  ) |>
  select(-starts_with("phase_")) |> 
  pivot_wider(
    names_from = phase,
    values_from = c(total_sec, session_pct, fullface_pct)
  ) |> 
  select(emotion, ends_with("_I"), ends_with("_II")) |> 
  mutate(emotion = str_to_title(emotion)) |> 
  gt() |> 
    tab_spanner(
      label = "Phase I",
      columns = ends_with("_I")
    ) |> 
    tab_spanner(
      label = "Phase II",
      columns = ends_with("_II")
    ) |> 
  cols_label(
    emotion = "Emotion",
    starts_with("total_sec") ~ "Total (Sec)",
    starts_with("session") ~ "Session (%)",
    starts_with("fullface") ~ "Full Face (%)"
  ) |> 
  grand_summary_rows(
    columns = -emotion,
    fns = list(Total = ~sum(., na.rm = TRUE)),
    fmt = list(
      ~ fmt_percent(., columns = matches("pct"), decimals = 2),
      ~ fmt_number(., columns = matches("total"), decimals = 1)
    )
  ) |>
  fmt_percent(
    columns = matches("pct"), 
    decimals = 2
  ) |> 
  fmt_number(
    columns = matches("total"),
    decimals = 1
  )
```

## Model Prototypes

```{r}
occ_counts_long <- 
  occ_counts |> 
  # Sort chronologically within each grouping
  arrange(subject, wave, occ, facs_onset) |> 
  mutate(
    .by = c(subject, wave, occ),
    # Find the maximum offset time seen prior to the current row
    max_offset_so_far = cummax(lag(facs_offset, default = -Inf)),
    # Start a new block if current onset happens after the latest offset
    is_new_block = facs_onset > max_offset_so_far,
    # Assign a unique ID to each continuous block of time
    block_id = cumsum(is_new_block)
  ) |> 
  # Collapse each block into a single, merged start and end time
  summarize(
    .by = c(subject, wave, occ, block_id),
    merged_onset = min(facs_onset),
    merged_offset = max(facs_offset)
  ) |> 
  # Calculate the duration of the distinct blocks
  mutate(block_duration = merged_offset - merged_onset) |> 
  # Sum the blocks to get the final, accurate duration
  summarize(
    .by = c(subject, wave, occ),
    occ_duration = sum(block_duration)
  )
```

```{r}
protos_distinct <- 
  protos2 |> 
  drop_na(emotion) |> 
  distinct(emotion, remaining_aus) |> 
  mutate(remaining_aus = coding(remaining_aus))

emotion_events <- 
  occ_counts |> 
  inner_join(
    y = protos_distinct,
    by = join_by(occ == remaining_aus),
    relationship = "many-to-many"
  ) |> 
  arrange(subject, wave, emotion, facs_onset) |> 
  mutate(
    .by = c(subject, wave, emotion),
    max_offset_so_far = cummax(lag(facs_offset, default = -Inf)),
    is_new_block = facs_onset > max_offset_so_far,
    block_id = cumsum(is_new_block)
  ) |> 
  summarize(
    .by = c(subject, wave, emotion, block_id),
    merged_onset = min(facs_onset),
    merged_offset = max(facs_offset)
  ) |> 
  mutate(block_duration = merged_offset - merged_onset) |> 
  summarize(
    .by = c(subject, wave, emotion),
    occ_duration = sum(block_duration)
  )
```

```{r}
emotion_long <- 
  crossing(
    subject = unique(info$subject),
    wave = unique(info$wave),
    emotion = unique(protos_distinct$emotion)
  ) |> 
  left_join(emotion_events, by = join_by(subject, wave, emotion)) |> 
  replace_na(list(occ_duration = 0)) |> 
  left_join(
    y = info |> select(subject, phase, wave, valid_session, valid_fullface),
    by = join_by(subject, wave)
  ) |> 
  mutate(
    session_pct = occ_duration / valid_session,
    fullface_pct = occ_duration / valid_fullface
  ) |> 
  mutate(
    .by = c(phase, emotion),
    m_pct = sum(occ_duration, na.rm = TRUE) / sum(valid_fullface, na.rm = TRUE)
  ) |> 
  filter(m_pct >= 0.01)
```

### Phase I

```{r}
emotion_wide_i <- 
  emotion_long |> 
  filter(phase == "I") |> 
  pivot_wider(
    names_from = emotion,
    values_from = fullface_pct,
    id_cols = c(subject, wave)
  ) |> 
  mutate(
    subject = factor(subject),
    wave,
    Wave = factor(wave), 
    .after = 1
  )
summary(emotion_wide_i)
```

```{r}
#| message: false
#| warning: false

dvs <- emotion_wide_i |> select(-subject, -wave, -Wave) |> colnames()

models_I <- 
  map(
    dvs,
    \(x) {
      ordbetareg(
        formula = as.formula(
          paste0(x, " ~ 1 + Wave + (1 | subject)")
        ),
        data = emotion_wide_i,
        coef_prior_mean = 0,
        coef_prior_SD = 1.5,
        chains = 4,
        cores = 4,
        refresh = 0,
        backend = "cmdstanr",
        file = paste0("fit_I_", x),
        control = list(adapt_delta = 0.9)
      )
    }
  ) |> 
  set_names(str_to_title(dvs))
```

```{r}
#| message: false

res_I <- 
  map(
    models_I,
    \(x) { 
      describe_posterior(x, parameters = "Wave") |> 
      as_tibble() |> 
      transmute(
        Est. = Median,
        CL = CI_low,
        CU = CI_high,
        OR = exp(Est.),
        OR_CL = exp(CL),
        OR_CU = exp(CU),
        pval = 2*(1 - pd)
      )
    }
  ) |> 
  set_names(str_to_title(dvs)) |> 
  list_rbind(names_to = "Outcome") |> 
  mutate(.before = 1, Phase = "I")

gt(res_I) |> 
  tab_header(
    title = md("Contrast: Wave 9 -- Wave 6")
  ) |> 
  fmt_number(
    columns = Est.:OR_CU, 
    decimals = 2
  ) |> 
  fmt(
    columns = pval,
    fns = \(x) {
      char_x <- sprintf("%.3f", x)
      char_x <- sub("^0\\.", ".", char_x)
      ifelse(x < 0.001, "<.001", char_x)
    }
  ) |> 
  cols_merge(
    columns = c(Est., CL, CU),
    pattern = "{1} ({2}, {3})"
  ) |> 
  cols_merge(
    columns = c(OR, OR_CL, OR_CU),
    pattern = "{1} ({2}, {3})"
  ) |> 
  cols_label(
    Est. = "Logit Scale",
    OR = "Odds Ratio",
    pval = "p-value"
  ) |> 
  cols_align(
    align = "center",
    columns = c(Est., OR)
  )
```

### Phase II

```{r}
emotion_wide_ii <- 
  emotion_long |> 
  filter(phase == "II") |> 
  pivot_wider(
    names_from = emotion,
    values_from = fullface_pct,
    id_cols = c(subject, wave)
  ) |> 
  mutate(
    subject = factor(subject),
    wave,
    Wave = factor(wave), 
    .after = 1
  )
summary(emotion_wide_ii)
```

```{r}
#| message: false
#| warning: false

dvs <- emotion_wide_ii |> select(-subject, -wave, -Wave) |> colnames()

models_II <- 
  map(
    dvs,
    \(x) {
      ordbetareg(
        formula = as.formula(
          paste0(x, " ~ 1 + Wave + (1 | subject)")
        ),
        data = emotion_wide_ii,
        coef_prior_mean = 0,
        coef_prior_SD = 1.5,
        chains = 4,
        cores = 4,
        refresh = 0,
        backend = "cmdstanr",
        file = paste0("fit_II_", x),
        control = list(adapt_delta = 0.9)
      )
    }
  ) |> 
  set_names(str_to_title(dvs))
```

```{r}
res_II <- 
  map(
    models_II,
    \(x) { 
      describe_posterior(x, parameters = "Wave") |> 
      as_tibble() |> 
      transmute(
        Est. = Median,
        CL = CI_low,
        CU = CI_high,
        OR = exp(Est.),
        OR_CL = exp(CL),
        OR_CU = exp(CU),
        pval = 2*(1 - pd)
      )
    }
  ) |> 
  set_names(str_to_title(dvs)) |> 
  list_rbind(names_to = "Outcome") |> 
  mutate(.before = 1, Phase = "II")

gt(res_II) |> 
  tab_header(
    title = md("Contrast: Wave 15 -- Wave 12")
  ) |> 
  fmt_number(
    columns = Est.:OR_CU, 
    decimals = 2
  ) |> 
  fmt(
    columns = pval,
    fns = \(x) {
      char_x <- sprintf("%.3f", x)
      char_x <- sub("^0\\.", ".", char_x)
      ifelse(x < 0.001, "<.001", char_x)
    }
  ) |> 
  cols_merge(
    columns = c(Est., CL, CU),
    pattern = "{1} ({2}, {3})"
  ) |> 
  cols_merge(
    columns = c(OR, OR_CL, OR_CU),
    pattern = "{1} ({2}, {3})"
  ) |> 
  cols_label(
    Est. = "Logit Scale",
    OR = "Odds Ratio",
    pval = "p-value"
  ) |> 
  cols_align(
    align = "center",
    columns = c(Est., OR)
  )
```
