---
title: "Occlusion Coding"
author: "Jeffrey Girard"
date: "2026-04-27"
format: 
  html:
    page-layout: full
    fig-width: 10
    fig-format: png
    fig-dpi: 150
embed-resources: true
---

```{r}
#| message: false
#| label: setup

library(tidyverse)
library(readxl)
```

```{r}
dat <- read_xlsx(
  "/mnt/datasets/SEEDLingS/1_RAWDATA/FACS/FACS_code_inventory.xlsx", 
  sheet = 2,
  na = c("", "NA", "nan"),
  .name_repair = janitor::make_clean_names
)
```

```{r}
dat2 <- 
  dat |> 
  select(
    subject = id, 
    starts_with("fullfaceavail_"),
    starts_with("no_facs"), 
    starts_with("no_fac_sn"), 
    starts_with("facs_tot_")
  ) |> 
  pivot_longer(-subject) |> 
  mutate(
    name = str_replace(name, "fullfaceavail_", "ffa"),
    name = str_remove(name, "no_facs_"),
    name = str_replace(name, "no_fac_sn_", "neu"),
    name = str_replace(name, "facs_tot_", "auc"),
    var = str_sub(name, 1, 3),
    wave = parse_number(name)
  ) |> 
  select(-name) |> 
  pivot_wider(names_from = var, values_from = value) |> 
  mutate(neu = if_else(neu < 0, NA, neu))
```

```{r}
write_rds(dat2, "facs_times.rds")
```

```{r}
dat2 |> 
  pivot_longer(vis:auc, names_to = "type", values_to = "sec") |> 
  drop_na() |> 
  summarize(.by = c(wave, type), sec = sum(sec)) |> 
  mutate(
    wave = factor(wave),
    type = case_when(
      type == "auc" ~ "Any Other AU",
      type == "neu" ~ "AU0 Neutral",
      type == "hat" ~ "Hat Occlusion",
      type == "vis" ~ "Other Occlusion"
    ),
    type = factor(type, levels = c("Other Occlusion", "Hat Occlusion", "AU0 Neutral", "Any Other AU"))
  ) |> 
  ggplot(aes(x = wave, y = sec, fill = type)) +
  geom_col(position = "fill", color = "black") +
  scale_fill_manual(values = c("grey30", "grey60", "white", "steelblue")) +
  scale_x_discrete(
    labels = c("6-8 months", "9-11 months", "12-14 months", "15-17 months")
  ) +
  scale_y_continuous(labels = scales::percent) +
  labs(
    x = "Age Window",
    y = "Proportion of Frames with a Full Face",
    fill = "Type"
  ) + 
  theme_bw(base_size = 10)
ggsave(filename = "fig1.png", width = 6.5, height = 4.0, units = "in", dpi = 300)
```

```{r}
dat2 |> 
  pivot_longer(vis:auc, names_to = "type", values_to = "sec") |> 
  drop_na() |> 
  summarize(.by = c(wave, type), sec = sum(sec)) |> 
  mutate(
    wave = factor(wave),
    type = case_when(
      type == "auc" ~ "Any Other AU",
      type == "neu" ~ "AU0 Neutral",
      .default = NA_character_
    ),
    type = factor(type, levels = c("AU0 Neutral", "Any Other AU"))
  ) |> 
  drop_na() |> 
  ggplot(aes(x = wave, y = sec, fill = type)) +
  geom_col(position = "fill", color = "black") +
  scale_fill_manual(values = c("white", "steelblue")) +
  scale_y_continuous("proportion", labels = scales::percent) +
  labs(title = "Frames with a Codeable Full Face")
```

```{r}
dat |> 
  select(
    subject = id,
    starts_with("facs_")
  ) |> 
  pivot_longer(-subject, names_prefix = "facs_") |> 
  separate_wider_delim(name, delim = "_", names = c("target", "wave")) |>
  pivot_wider(names_from = target, values_from = value) |> 
  mutate(
    sum = rowSums(pick(f1:f3), na.rm = TRUE),
    match = near(sum, tot, tol = 1e-10)
  )
```

```{r}
dat |> 
  select(
    subject = id,
    starts_with("facs_")
  ) |> 
  pivot_longer(-subject, names_prefix = "facs_") |> 
  separate_wider_delim(name, delim = "_", names = c("target", "wave")) |> 
  drop_na() |> 
  filter(target != "tot") |> 
  summarize(
    .by = c(wave, target),
    total_sec = sum(value)
  ) |> 
  mutate(wave = factor(parse_number(wave))) |> 
  ggplot(aes(x = wave, y = total_sec, fill = target)) +
  geom_col(position = "fill") +
  scale_fill_manual(
    values = c(
      "c1" = "#bae4b3",
      "c2" = "#74c476",
      "c3" = "#238b45",
      "f1" = "#fcae91",
      "f2" = "#fb6a4a",
      "f3" = "#cb181d",
      "m1" = "#bdd7e7",
      "m2" = "#6baed6",
      "self" = "black"
    )
  ) +
  scale_y_continuous("proportion", labels = scales::percent)
```

